apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: https-demo-ip
    networking.gke.io/managed-certificates: example-certificate
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: my-np-service
          servicePort: 80